### ISSUE TITLE
Switch crashes after I updated to 18.1.0

### ISSUE THREAD

**Issue by Jayacheal** [o0Zz/sys-con#15]
Panic occurred while running atmosphere.

Title ID: 690000000000000D
Error:     std::abort (0xFFE)

here is the fatal error report in case you need it: [report_0ebaed06.zip](https://github.com/user-attachments/files/15860085/report_0ebaed06.zip)

**Comment by texita** [comment]
That's because of sys-con version mismatching atmosphere version.

if you are on atmosphere 1.6.x use this:
https://github.com/o0Zz/sys-con/releases/download/1.1.1/sys-con-1.1.1-ATMOSPHERE-1.6.2.zip

if you are on atmosphere 1.7.x use this:
https://github.com/o0Zz/sys-con/releases/download/1.1.1/sys-con-1.1.1-ATMOSPHERE-1.7.0.zip

or simply delete the sys-con folder in sdmc:/atmosphere/contents/690000000000000D and your atmosphere will be booting again

**Comment by Jayacheal** [comment]
I am using atmosphere 1.7.1 and I did download the version made for 1.7.0, it was working before I updated the firmware from 18.0.1 to 18.1.0.
I did delete the sys-con folder to boot but that doesn't solve my problem since I want to use sys-con.

**Comment by o0Zz** [comment]
Could you please check if this build fix your crash ? (It has been build with the latest atmosphere lib), Thanks
[sys-con-1.1.1+15-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/15876161/sys-con-1.1.1%2B15-ATMOSPHERE-1.7.x.zip)

**Comment by Jayacheal** [comment]
this fixed the crash and everything is working as intended, thanks!
