### ISSUE TITLE
Automatically add the handle ID to the configuration file

### ISSUE THREAD

**Issue by Zhuwenxue2002** [o0Zz/sys-con#17]
Hello, could you consider setting Xbox360 as the default configuration? This solves most of the unofficial controllers with Xbox mode, which can be plug and play
Because I pull your plugin into the modpack, the 'config.ini' file is updated every time

**Comment by Zhuwenxue2002** [comment]
I updated to 1.7.1 atmosphere and 18.1.0 system
We look forward to Syscon's continued support

**Comment by o0Zz** [comment]
Could you please rename the title of your issue and use a title that summarize you issue. Exemple: "feature: automatic add controllers". It will help others to identify quickly if a question has already been answer ;).

Regarding you auto add feature, this is something that has already been requested by @texita. This is something I clearly connsider. Not exactly the way you consider because using xbox360 by default will only be valid for your cases and not for others but i will try to consider somethimg more generic here. Keep you issue open I will update it when the festure will be ready.

**Comment by Zhuwenxue2002** [comment]
Okay, I'm sorry, I'm a developer from China and I'm using translation software to communicate with you, so it's hard to name the title

**Comment by Zhuwenxue2002** [comment]
There are a large number of so-called 'domestic controllers' in China, and they are basically all in an Xbox layout, with an Xbox and PS model

**Comment by o0Zz** [comment]
The latest release include an auto add controller feature where controller are automatically added and sys-con try to determine the best profile for each controller:

https://github.com/o0Zz/sys-con/releases
