### ISSUE TITLE
Original Nintendo Switch: Pro Controller not working

### ISSUE THREAD

**Issue by texita** [o0Zz/sys-con#31]
Atmosphere version: 1.7.1
Switch OS version:  17.0.1
Syscon version: 1.2.2 + 1.2.2+19
Controller: Original Nintendo switch pro controller ( HACAFSSKA )
https://www.amazon.com/Nintendo-Switch-Pro-Controller/dp/B01NAWKYZ0/

VID-PID: [057e-2009]
Controller has been recognized and auto added. In sync menu i can see it, but no buttons are working.
i tried both discovery mode 0 and 1.
Tryed with version 1.2.2 and latest 1.2.2+19
All logs are in trace mode
Made a wireshark dump (anyway this pad in windows is not working, i can see the buttons in joy.cpl but if pressed nothing happen)

in the logs you will also see the VID/PID of my hori battle pad, was only to try the controllers in sync menu.

EDIT: without sys-con enabled or with the old sys-con from Cathery, is not working, i mean it works only in wireless mode.

[logs-config-wsdump.zip](https://github.com/user-attachments/files/16537106/logs-config-wsdump.zip)

EDIT: I opened this only for testing pourpose, i'm borrowing this pad from a friend and just want to made some tests on sys-con, we are using it always in wireless mode, so if you want to close this ticket as incompatible is not a problem for me :)

**Comment by o0Zz** [comment]
Nice catch. I didn't realized it was possible to connect switch controller PRO via USB - I though it was only for charging.
It was funny to see nintendo expose an HID on their controller but it's a "garbage" HID that doesn't match real data. That's the reason why your windows and sys-con was stucks. At the end I end up by creating a specific driver for nintendo switch controllers. 
Here is the version ->
[sys-con-1.2.2+27-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16623897/sys-con-1.2.2%2B27-ATMOSPHERE-1.7.x.zip)

**Comment by texita** [comment]
I will get the controller back and try. Can i use the latest 1.3.0 or i need this specific one 1.2.2+22 you sent here?

**Comment by o0Zz** [comment]
1.3.0 is the same binary thus you can use the 1.3.0 version without any problem

**Comment by texita** [comment]
Just tested, everything seems ok but don't know really :) so what i've done for the logs:

Reboot the switch, went in sync menu, docked the switch and connect the usb to the pad, after some seconds the pad popped out automatically in sync menu and on the pad the green light is showing that is connected in wireless mode. At this ponit i've pressed A to quit the sync menu, just pressed sometimes button B to see something in the logs. anyway in sync menu now you will always see 1 pad and not 2 as before. I think there is no way to really test it, because this pad always wanna work in wireless mode, just by pressing any botton it try to connect to the switch.

logs are in trace mode
[log.log](https://github.com/user-attachments/files/16667850/log.log)

**Comment by o0Zz** [comment]
Thanks for the detailed tests. 
Discovery_mode=1 should be the equivalent of the old sys-con since this mode disable the detection of HID devices, it will only detect XBOX devices, thus theorirically it should be exactly the same.

In all your tests we can see that sys-con took control of your switch pro controller

![image](https://github.com/user-attachments/assets/e0028e6e-8f78-4c24-8934-7494c0c299cc)

And it forced the controller to behave as "USB" - this is the purpose of the 2nd buffer: 0x80 0x04.
However, I can see in your tests that the controller never send any data. while on my side (I also have an official pro controller) when I'm doing the same test, the controller send data to sys-con.

Maybe one difference one my side, I never ever pair this controller to my switch (This controller is used only with the Officiel Switch FW) and I never paired it with atmosphere version - That one of the difference

**Comment by texita** [comment]
Just tried with a new formatted SD. Put only atmsphere 1.7.1 and sys-con 1.3.0 both redownloaded from github now, same result :(

I'm trying with no controllers and pro paired wired communication off (tried also with on, same result)

![2024082101330200-57B4628D2267231D57E0FC1078C0596D](https://github.com/user-attachments/assets/7ea945c9-7f5c-4b6e-974c-c67e7911c2e1)

![2024082101323200-57B4628D2267231D57E0FC1078C0596D](https://github.com/user-attachments/assets/aa38dddd-52ed-4d57-a415-e759869aef91)
![2024082101325100-57B4628D2267231D57E0FC1078C0596D](https://github.com/user-attachments/assets/e50167fd-6df7-4807-8f6e-487e0287e38e)

As you see in the last image i've only 2 controllers paired with the original HOS (the 2 joycons on the switch)

In this way i can't use anymore the pro controller. If i want to i have to disable sys-con, connect with USB for the first time and it will be synchronized, then i can use again in wireless mode.

So i think now we can esclude atmosphere or other plugins conficts

**Comment by o0Zz** [comment]
I'm not sure to understand the difference between your setup and mine. 
In fact, I'm relying on this -> https://gist.github.com/ToadKing/30d65150410df13763f26f45abbd3700
This code is the minimal code needed for the pro controller to talk to the host. 

 I wondering if the issue is not related to a timing issue. Could you try this new version, I'm trying to read controller output between 2 commands: (0x80, 0x02) and (0x80, 0x04). We will see if it change something.

[sys-con-1.3.0+6-ATMOSPHERE-1.7.x.zip](https://github.com/user-attachments/files/16753381/sys-con-1.3.0%2B6-ATMOSPHERE-1.7.x.zip)

Thanks

**Comment by texita** [comment]
Well..You made this controller working even in discovery_mode=0 with this version! Great :) I attach logs if needed
[log.log](https://github.com/user-attachments/files/16756371/log.log)

OT: This pro controller is not working in windows without drivers, but like the gc WUP-028 it was working only in discovery_mode=1 i've seen that the same dev has made these drivers https://github.com/ToadKing/wii-u-gc-adapter do you think it will be possible to add support for discovery_mode=0 even for WUP-028 or is totally different?

**Comment by o0Zz** [comment]
Good news! ;)

Regarding your question, no, it's 2 different issues and I agree it's weird to have these differences.

For the WUP-028, the switch kernel takes ownership of this controller and when sys-con tries to open the interface, it is rejected by the switch. So sys-con has no chance to take control of this controller. And this is actually the same problem with all controllers that simulate official switch controllers.
My guess is that if the switch kernel sees an official switch controller, it will take it, otherwise it will skip it.


With the pro controller, It's a different story  this controller fake a HID device and the switch will not immediately take control on this controller. This is why sys-con can open the controller and use it. In fact this controller in USB mode is not supported by the switch, the switch only use USB mode to automatically pair the controller but once the controller is paired then all data will go through Bluetooth and not USB.
Sys-con changes this behaviour and asks the controller to send data via USB.

**Comment by texita** [comment]
Everything is clear, thanks :)
