### ISSUE TITLE
Playstation classic controller doesn't work when docked

### ISSUE THREAD

**Issue by vichorx** [o0Zz/sys-con#37]
Thank you for keeping this module alive

**Information**
Atmosphere version: 1.7.1
Switch OS version: 18.1.0
Syscon version: 1.4.1 
Controller: Playstation classic controller [054c-0cda]

**Description**
The controller works when connected through a USB-C to A adapter (from an old Samsung phone). When I connect it to the dock, it's not recognized. Other controllers, like the Street Figther V Arcade Fightstick Alpha for Ps3 & Ps4 and a Dualsense work when docked and with the adapter. 
Config.ini is lightly modified, as it setup b and x switched. 
On the log, when docked, the controller is not recognized ("No HID or XBOX interfaces found !") so it doesn't appear by it's VID or PID.

**Logs**
[log.log](https://github.com/user-attachments/files/17142517/log.log)
![image](https://github.com/user-attachments/assets/4acb1d07-76a5-499b-a5bd-4879ee2484dc)

**Comment by o0Zz** [comment]
Hi,
Thank you for this report. Could you provide a logs when its working (with the USB-C adapter) ?

**Comment by vichorx** [comment]
Sure, this is a log from right now, where I connected the controller and pressed a few directions, then disconnected it and, then reconnected it and pressed a few more directions and disconnected it again. 

[log.log](https://github.com/user-attachments/files/17143707/log.log)

**Comment by o0Zz** [comment]
After thoroughly reviewing your logs, I don't believe this is a software issue. It seems more likely to be a hardware problem, possibly due to insufficient power or a bad connection via USB.

Please disconnect any other controllers from the dock, ensuring that only the controller in question is plugged in. Let me know if this improves the situation. The goal here is to verify that your controller is receiving adequate power from the Switch. The dock has multiple USB ports, and if other devices are connected, they might be drawing power away from the controller.

Check for any loose connections when plugging your USB into the dock. You might want to try using a USB extender to see if that makes a difference. The idea here is to ensure that the USB connector is making proper contact with the dock.
For exemple, try to connect your extender then connect you PS3 to this extender (Make sure it works) then try the faulty controller.

Let me know if it improve things

**Comment by o0Zz** [comment]
Thank you for all your test. According to your last test, It seems that when a hub is placed between the switch and the controller, the switch is unable to recognise the controller. It's as if the hub is changing the behaviour of the switch. Sys-con has no control over this, as it relies on the Horizon OS, and the problem seems to come from the OS itself or a lower driver. Unfortunately, the only possible solution would be to patch the OS, which is beyond our scope.

**Comment by vichorx** [comment]
I understand. I still want to use my ps classic controller on the switch but I don't really know what to try. Thank you for taking time to check this out and helping me. And thanks again for maintaining the module.
