### ISSUE TITLE
XBOX 360 wireless receiver for PC

### ISSUE THREAD

**Issue by ArieSneek** [o0Zz/sys-con#42]
**Information**
Atmosphere version: 1.8.0
Switch OS version: 19.0.0
Syscon version: 1.4.2
Controller: Xbox 360 wireless receiver for PC

**Description**
Nothing happens on my Switch. I tried dock and also OTG. The log doesn't show anything.
I've edited the config and added my receiver [045E-02AA] , but still nothing.
The receiver works fine in Windows with the standard driver (XBOX 360 receiver)
I've also tried the +1 version that you've posted in the other issue post, but that doesn't work either

**Logs**
Nothing in the logs no detection
The receiver in windows is [045E-02AA]

**Comment by o0Zz** [comment]
It seems you got the same issue than: #42 and #30, Controllers are not detected at all by the switch. Unfortunately sys-con cannot fix that because it's a low level issue between the switch and the controller, indeed the switch OS doesn't detect the USB and thus don't signal at the upper layer that something happened.

**Comment by ArieSneek** [comment]
Thanks for your reply. I think it's the USB-C on the Switch that maybe kinda broken. I mean it charges and it docks, but when I connect the Switch to my pc (tried also 2 laptops) it says unknown and it even freezes a laptop when I connect it.

**Comment by o0Zz** [comment]
Ok great if you found the root cause, I'm not sure if the "XBOX 360 wireless receiver" using here is the official one, but clearly I have this one on my side and everything works fine.
