### ISSUE TITLE
Controller is detected, but vanishes at the same second

### ISSUE THREAD

**Issue by edvdourado** [o0Zz/sys-con#50]
**Information**
Atmosphere version: 1.7.x-1.8.x-989fb7be
Switch OS version: 18.1.0
Syscon version: 1.4.3+0-0682ed5
Controller: [045e-028e]

**Description**
I'm trying to connect a xbox controller [045e-028e] and when I first connected it showed up at the controllers section on switch, but immediately vanishes, like if it's detected only for a milisecond.

I took a look at the log and saw the error |E| "Failed to acquire USB interface - Error: 0x25A8C (Module: 0x8C, Desc: 0x12D)", and then proceeded to change discovery_mode to 1 and the range to "discovery_vidpid=045e-*,045e-028e".

Rebooted the console, tried again, but now it doesn't even show up for a milisecond as last time.
Changed the log to Trace and tried again, but it stays the same.
Can you help me? 
Thanks in advance!!!
[log.txt](https://github.com/user-attachments/files/17597530/log.txt)

**Comment by o0Zz** [comment]
Hi, 

In order to attach log and ini you need to zip them or rename them to .txt.

Did you try your controller on a PC to make sure this controller works properly ?  It look like this controller has an issue.

If Yes, Could you re-set 
```
discovery_mode=0
log_lvl=0
```

And try to reproduce your issue. In the log trace your provided, you didn't reproduced the issue thus the logs are not usefull.

**Comment by edvdourado** [comment]
Hi!

Thanks for the feedback.

Tested the controller again, works absolutely fine on PC!

I re-set discovery mod and log_level to 0, the controller [045e-028e] was detected again as first time and also disappeared right after. What I forgot to mention is that the lights on the controller are ON, as if it knows it has been detected, but no inputs work on the switch since it vanishes.

here's the full log.log and config.ini (now in .txt).
[config.txt](https://github.com/user-attachments/files/17600482/config.txt)
[log.txt](https://github.com/user-attachments/files/17600483/log.txt)

**Comment by o0Zz** [comment]
Could you please confirm you only plugged the xbox controller ? 
I see another controller: 2563-0575. Is this controller properly works ?

Regarding 045e-028e, I can see it is properly detected and stay connected for a while, but it look like it's not displayed on the  switch because the switch don't receive any input from this controller. Did you try to press a button after the led was power on ?

(Led is on means sys-con properly detected it and send the correct initialization sequence)

**Comment by edvdourado** [comment]
Sorry for not addressing it, I also used the Switch own joycons to turn it up, so I think the 2563-0575 are the joycons

Yes! I tried pressing every single button, including L + R as the switch tells me to press it when it recognizes and vanishes

**Comment by edvdourado** [comment]
I'm so ashamed right now.

I looked at the back of the controller and there was a switch and when I turned the switch, the Nintendo Switch just detected it, it's working! LOOOOL

But the inputs are very very slow, I press a button and the switch only recognizes the button after a second, is there a way to make it faster?

**Comment by o0Zz** [comment]
OK great if it works, 2563-0575 is not the official switch controller. Maybe your controller expose 2 interfaces.

I think your controller is: "Double Shock Fighter USB 2.0 Dazz" which is not the official xbox controller, you should have started by that.

With DInput I think you will have to map your buttons, do not hesitate to share your configuration once done.

For the lag, as state in the documentation, you have to use log_lvl=2 (log_lvl=0 cause the polling frequency to be slow))

**Comment by edvdourado** [comment]
update: Did not need to map the buttons, everything now works perfectly!

I will be closing the issue, thanks again =)
