### ISSUE TITLE
Sysmodule does not de-init properly

### ISSUE THREAD

**Issue by Craftyawesome** [o0Zz/sys-con#52]
**Information**
Atmosphere version: 1.8.0
Switch OS version: 19.0.1
Syscon version: 1.4.3
Controller: (NA / only joycons connected)

**Description**
When using something like ovl-sysmodules to stop the sysmodule without rebooting, the memory usage does not decrease. Turning it on again will decrease free memory.

But even with seemingly enough free memory, the 4th attempt to load sys-con will cause atmosphere to panic.

If this is an intentional compromise to avoid requiring a reboot, it should be added to the readme.

**Logs**
Not much help, it initializes 3 times normally but crashes before any output on the 4th try.
[(useless) log+config.zip](https://github.com/user-attachments/files/17780797/useless.log%2Bconfig.zip)

**Comment by o0Zz** [comment]
Hi thanks for the report, I will have a look, I'm not really surprise by this finding, I never took the time to unitialize the module properly.

**Comment by o0Zz** [comment]
The new version, v1.5.0, does not fully resolve this issue but prevents the crash from occurring. This issue is a known limitation in Horizon OS and ovl-sysmodule, which cannot be addressed directly by sys-con. A broader solution from the community would be required to fix this limitation.

The [Troubleshooting Guide](https://github.com/o0Zz/sys-con/blob/master/doc/Troubleshooting.md#stopping-sys-con-with-ovl-sysmodule-does-not-restore-memory-and-stops-working-after-3-attempts) has been updated accordingly.
